# Generated by Django 2.2.6 on 2019-10-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('document', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('registrationDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('teacher', 'teacher')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(choices=[('morning', 'morning'), ('afternoon', 'afternoon')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Employee')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Grade')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='workingDay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.WorkingDay'),
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.ManyToManyField(through='college.Holder', to='college.Grade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workingDay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.WorkingDay'),
        ),
    ]
