# Generated by Django 2.2.6 on 2019-10-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='document',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
