# Generated by Django 2.2.6 on 2019-10-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20191026_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
